name: Validate
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v7.0.0
        with:
          python-version: '3.14'
          cache: pip
      - run: pip install -r requirements-test.txt
      - run: ruff check .
      - run: ruff format --check .
      - run: pytest --cov-fail-under=95
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: home-assistant/actions/hassfest@master
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: hacs/action@main
        with:
          category: integration
